const PLATFORM = (() => { const host = window.location.hostname; if (host.includes('claude.ai')) return 'claude'; if (host.includes('chatgpt.com')) return 'chatgpt'; if (host.includes('gemini.google.com')) return 'gemini'; return 'unknown'; })();
console.log('[ContextLens] Active on ' + PLATFORM);
(function injectMainWorld() { const s = document.createElement('script'); s.src = chrome.runtime.getURL('injector.js'); s.onload = () => s.remove(); (document.head || document.documentElement).appendChild(s); })();
let sessionTokensSaved = 0, chatTokensSaved = 0, totalTokensSaved = 0, compressionCount = 0, lastConvId = null, lastActivityTs = Date.now();
const SESSION_TIMEOUT_MS = 30 * 60 * 1000;
const PROXY_BASE = 'https://contextlens.65.108.217.183.nip.io';
const SELECTORS = { claude: { messages: '[class*="font-user-message"], [class*="standard-markdown"]', humanMessage: '[class*="font-user-message"]' }, chatgpt: { messages: '[data-message-author-role]', humanMessage: '[data-message-author-role="user"]' }, gemini: { messages: '.conversation-container .turn', humanMessage: '.user-turn' } };
function hashString(str) { let hash = 0; for (let i = 0; i < str.length; i++) { hash = ((hash << 5) - hash) + str.charCodeAt(i); hash = hash & hash; } return hash.toString(); }
function compressLocal(messages) { if (!messages || messages.length < 3) return { tokens_saved_estimate: 0 }; const originalChars = messages.reduce((s, m) => s + m.content.length, 0); const seen = new Map(); const result = []; for (let i = 0; i < messages.length; i++) { const msg = messages[i]; const isLast = i === messages.length - 1; if (isLast) { result.push(msg); continue; } const hash = hashString(msg.content); if (seen.has(hash)) continue; seen.set(hash, true); result.push(msg); } const saved = Math.max(0, originalChars - result.reduce((s, m) => s + m.content.length, 0)); return { tokens_saved_estimate: Math.round(saved / 4) }; }
function readConversation() { const sel = SELECTORS[PLATFORM]; if (!sel) return []; const elements = document.querySelectorAll(sel.messages); const messages = []; elements.forEach(el => { const isHuman = el.matches(sel.humanMessage) || el.getAttribute('data-message-author-role') === 'user'; const content = el.innerText?.trim(); if (content && content.length > 0) messages.push({ role: isHuman ? 'user' : 'assistant', content }); }); return messages; }
function runCompression(messages, onResult) { fetch(PROXY_BASE + '/compress', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: messages, threshold: 0.82 }) }).then(r => r.json()).then(data => { console.log('[ContextLens] Semantic: ' + data.redundancy_pct + '% redundancy'); onResult(data.tokens_saved_estimate || 0); }).catch(() => { onResult(compressLocal(messages).tokens_saved_estimate || 0); }); }
function showIndicator(t) { try { const ex = document.getElementById('cl-indicator'); if (ex) ex.remove(); const el = document.createElement('div'); el.id = 'cl-indicator'; el.style.cssText = 'position:fixed;bottom:80px;right:20px;background:#1a1a2e;color:#00ff88;padding:10px 16px;border-radius:8px;font-family:monospace;font-size:12px;z-index:99999;border:1px solid #00ff88;line-height:1.8;box-shadow:0 4px 12px rgba(0,255,136,0.2);cursor:pointer;transition:opacity 0.3s'; el.innerHTML = '<strong>⚡ ContextLens</strong><br>This response: ~' + t + ' tokens saved<br>This chat: ~' + chatTokensSaved + ' tokens saved<br>This session: ~' + sessionTokensSaved + ' tokens saved<br><span style="font-size:10px;color:#00cc6a">▼ click to view memory</span>'; document.body.appendChild(el); let ft = setTimeout(() => { el.style.opacity='0'; setTimeout(() => el.remove(), 500); }, 4000); el.addEventListener('mouseenter', () => { clearTimeout(ft); el.style.opacity='1'; }); el.addEventListener('mouseleave', () => { ft = setTimeout(() => { el.style.opacity='0'; setTimeout(() => el.remove(), 500); }, 2000); }); el.addEventListener('click', () => { clearTimeout(ft); el.remove(); showMemoryPanel(); }); } catch(e) {} }
function renderPanelTurns(allTurns, query) { const body = document.getElementById('cl-panel-body'); if (!body) return; const q = (query||'').toLowerCase().trim(); const filtered = q ? allTurns.filter(t => (t.assistantText||'').toLowerCase().includes(q) || (t.userText||'').toLowerCase().includes(q)) : allTurns; const turns = filtered.slice(0,15); if (turns.length === 0) { body.innerHTML = '<div style="color:#6b6b80;text-align:center;padding:20px">' + (q ? 'No results for "'+q+'"' : 'No memory yet.<br>Send a message to start.') + '</div>'; return; } body.innerHTML = turns.map(t => { const time = new Date(t.ts).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}); const userMsg = t.userText ? '<div style="color:#4488ff;font-size:10px;margin-bottom:3px">▶ ' + (t.userText).slice(0,80) + (t.userText.length>80?'…':'') + '</div>' : ''; const text = (t.assistantText||'').slice(0,100)+'…'; const cid = t.convId||''; return '<div data-conv-id="'+cid+'" style="background:#111118;border:1px solid #2a2a3a;border-radius:6px;padding:8px 10px;margin-bottom:6px;cursor:pointer"><div style="color:#00ff88;font-size:10px;margin-bottom:4px">'+(t.platform||'unknown')+' · '+time+(t.pinned?' · ★':'')+' </div>'+userMsg+'<div style="color:#9999b0;line-height:1.5">'+text+'</div></div>'; }).join(''); body.querySelectorAll('[data-conv-id]').forEach(card => { card.addEventListener('click', () => { const id = card.getAttribute('data-conv-id'); if (id) window.open('https://claude.ai/chat/'+id,'_blank'); }); }); }
function showMemoryPanel() { try { const ex = document.getElementById('cl-panel'); if (ex) { ex.remove(); return; } const panel = document.createElement('div'); panel.id = 'cl-panel'; panel.style.cssText = 'position:fixed;bottom:80px;right:20px;width:340px;max-height:420px;background:#0a0a0f;border:1px solid #00ff88;border-radius:10px;font-family:monospace;font-size:12px;z-index:999999;box-shadow:0 8px 32px rgba(0,255,136,0.15);overflow:hidden;display:flex;flex-direction:column'; const hdr = document.createElement('div'); hdr.style.cssText = 'padding:12px 14px;border-bottom:1px solid #2a2a3a;background:#111118'; hdr.innerHTML = '<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><span style="color:#00ff88;font-weight:bold">⬡ ContextLens Memory</span><span id="cl-panel-close" style="color:#6b6b80;cursor:pointer;font-size:14px">✕</span></div><input id="cl-panel-search" type="text" placeholder="Search memory..." style="width:100%;background:#0a0a0f;border:1px solid #2a2a3a;border-radius:5px;padding:6px 10px;color:#e8e8f0;font-family:monospace;font-size:11px;outline:none">'; const body = document.createElement('div'); body.id = 'cl-panel-body'; body.style.cssText = 'overflow-y:auto;padding:10px;flex:1'; body.innerHTML = '<div style="color:#6b6b80;text-align:center;padding:20px">Loading...</div>'; panel.appendChild(hdr); panel.appendChild(body); document.body.appendChild(panel); document.getElementById('cl-panel-close').addEventListener('click', () => panel.remove()); document.addEventListener('keydown', function esc(e) { if (e.key==='Escape') { panel.remove(); document.removeEventListener('keydown', esc); } }); if (!chrome?.storage?.local) { body.innerHTML = '<div style="color:#6b6b80;text-align:center;padding:20px">Refresh page to use memory.</div>'; return; } chrome.storage.local.get(['cl_turns'], data => { const allTurns = (data.cl_turns||[]).slice().reverse(); renderPanelTurns(allTurns,''); const si = document.getElementById('cl-panel-search'); if (si) { si.addEventListener('input', () => renderPanelTurns(allTurns, si.value)); setTimeout(() => si.focus(), 100); } }); } catch(e) {} }
function sendToProxy(convId, assistantText, userText) { try { if (!chrome?.runtime?.id) return; chrome.storage.local.get(['cl_proxy_url'], data => { const url = data.cl_proxy_url || PROXY_BASE+'/ingest2'; fetch(url, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({convId, platform:PLATFORM, assistantText, userText:userText||'', ts:new Date().toISOString()}) }).then(r=>r.json()).then(d=>console.log('[ContextLens] Proxy stored turn:',d.id)).catch(e=>console.warn('[ContextLens] Proxy send failed:',e)); }); } catch(e) {} }
function saveToLocalMemory(convId, assistantText, userText) { try { if (!chrome?.runtime?.id) return; if (!chrome?.storage?.local) return; const turn = { id:crypto.randomUUID(), convId, platform:PLATFORM, assistantText, userText:userText||'', ts:new Date().toISOString(), pinned:false, tags:[] }; chrome.storage.local.get(['cl_turns','cl_user_id'], data => { try { let uid = data.cl_user_id; if (!uid) { uid=crypto.randomUUID(); chrome.storage.local.set({cl_user_id:uid}); } let turns = data.cl_turns||[]; if (turns.some(t=>t.assistantText===assistantText)) return; turns.push(turn); if (turns.length>500) turns = turns.filter(t=>t.pinned).concat(turns.filter(t=>!t.pinned).slice(-500)); chrome.storage.local.set({cl_turns:turns}); console.log('[ContextLens] Saved turn. Total: '+turns.length); } catch(e) {} }); } catch(e) {} }
function watchSendButton() { const start = () => { if (!document.body) return; new MutationObserver(()=>{}).observe(document.body,{childList:true,subtree:true}); console.log('[ContextLens] MutationObserver active (silent)'); }; if (document.body) start(); else document.addEventListener('DOMContentLoaded', start); }
function watchKeyboard() { document.addEventListener('keydown', e => { if ((e.ctrlKey||e.metaKey) && e.key==='Enter') { try { if (!chrome?.runtime?.id) return; const msgs = readConversation(); if (msgs.length<2) return; runCompression(msgs, t => { chatTokensSaved+=t; sessionTokensSaved+=t; totalTokensSaved+=t; compressionCount++; showIndicator(t); chrome.storage.local.set({cl_tokens_saved:totalTokensSaved,cl_calls:compressionCount}); }); } catch(e) {} } }, true); }
chrome.runtime.onMessage.addListener((msg,sender,sendResponse) => { if (msg.type==='GET_POPUP_STATS') sendResponse({sessionTokensSaved,chatTokensSaved,totalTokensSaved,calls:compressionCount,platform:PLATFORM,messagesInConversation:readConversation().length}); return true; });
window.addEventListener('message', event => { try { if (event.source!==window) return; if (!event.data||event.data.type!=='__CONTEXTLENS_TURN_COMPLETE__') return; if (!chrome?.runtime?.id) return; if (!chrome?.storage?.local) return; const {convId,assistantText,userText=''} = event.data; console.log('[ContextLens] Turn captured:',convId,assistantText.slice(0,80)); const now=Date.now(); if (now-lastActivityTs>SESSION_TIMEOUT_MS) sessionTokensSaved=0; lastActivityTs=now; if (convId!==lastConvId) { chatTokensSaved=0; lastConvId=convId; } sendToProxy(convId,assistantText,userText); saveToLocalMemory(convId,assistantText,userText); const messages=readConversation(); if (messages.length<2) return; runCompression(messages, t => { chatTokensSaved+=t; sessionTokensSaved+=t; totalTokensSaved+=t; compressionCount++; chrome.storage.local.set({cl_tokens_saved:totalTokensSaved,cl_calls:compressionCount}); showIndicator(t); }); } catch(e) { console.warn('[ContextLens] SSE handler error:',e); } });
watchSendButton();
watchKeyboard();
console.log('[ContextLens] DOM observer active');
